[package]
name = "rusty_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg", "webp", "gif", "bmp", "tiff", "ico"] }
rfd = "0.14.1"
arboard = { version = "3.4.1", features = ["wayland-data-control"] }
env_logger = "0.11.3"
dirs = "6.0"
winit = "0.29"

[dev-dependencies]
tempfile = "3.10.1"